# Generated by Django 3.2.4 on 2021-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0009_auto_20210722_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consulta',
            name='hora',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
