# Generated by Django 3.2.4 on 2021-07-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0010_alter_consulta_hora'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='pendiente',
        ),
    ]
