# Generated by Django 3.2.6 on 2021-08-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0010_auto_20210724_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinica',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10),
        ),
        migrations.AlterField(
            model_name='consultorio',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10),
        ),
    ]
