# Generated by Django 3.2.4 on 2021-07-24 23:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0011_remove_cita_pendiente'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={'ordering': ('fechaCita',)},
        ),
        migrations.AddField(
            model_name='horario',
            name='activo',
            field=models.BooleanField(blank=True, default=1),
        ),
        migrations.AddField(
            model_name='horario',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Veterinaria.clinica'),
            preserve_default=False,
        ),
    ]
