# Generated by Django 3.2.6 on 2021-08-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0011_auto_20210802_0316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('idServicio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreServicio', models.CharField(max_length=100)),
                ('descServicio', models.CharField(max_length=150)),
                ('catServicio', models.CharField(max_length=30)),
                ('estadoServicio', models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=10)),
            ],
        ),
    ]
