# Generated by Django 3.2.4 on 2021-07-29 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0011_auto_20210728_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.consultorio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expediente',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.consultorio'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expediente',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica'),
            preserve_default=False,
        ),
    ]
