# Generated by Django 3.2.4 on 2021-07-31 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0012_auto_20210728_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='clinica',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.clinica'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consulta',
            name='consultorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Veterinaria.consultorio'),
            preserve_default=False,
        ),
    ]
