# Generated by Django 3.2.6 on 2021-08-03 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Veterinaria', '0012_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultorio',
            name='servicios',
        ),
        migrations.AddField(
            model_name='consultorio',
            name='servicio',
            field=models.ManyToManyField(to='Veterinaria.Servicio'),
        ),
        migrations.RemoveField(
            model_name='clinica',
            name='servicios',
        ),
        migrations.AddField(
            model_name='clinica',
            name='servicios',
            field=models.ManyToManyField(to='Veterinaria.Servicio'),
        ),
    ]
